### ISSUE TITLE
brainageR command not found

### ISSUE THREAD

**Issue by nicky9468** [james-cole/brainageR#10]
Hi,

I'm a beginner at working with codes and commands. I've tried to follow the instructions to set up brainageR, by making the directories, cloning the repository, downloading the 3 .rds files and editing the paths in the brainageR script. However, the terminal is still unable to recognise brainageR as a command.

Refer to images below for the path references:
brainageR_dir=/home/nicky155/Documents/brainageR/software/
spm_dir=/home/nicky155/Documents/MRI/SPM12/
matlab_path=/usr/local/MATLAB/R2023a/bin/matlab
FSLDIR=/home/nicky155/fsl/

![image](https://github.com/james-cole/brainageR/assets/110340502/29e7dc82-56fb-411b-b82a-ed599c4d359e)

![image](https://github.com/james-cole/brainageR/assets/110340502/bdde9b05-1802-4ddb-a1fc-2d2bad2ed9cf)

![image](https://github.com/james-cole/brainageR/assets/110340502/42bc0a8b-b545-4399-960b-58d406bd879a)

![image](https://github.com/james-cole/brainageR/assets/110340502/c16b65ad-771c-44bc-bf05-c1233aea27c0)

**Comment by james-cole** [comment]
Hi Nicky,

Thanks for your interest in brainageR. What error message are you getting exactly?

Is /home/nicky155/Documents/brainageR/software/ in your path (i.e., $PATH)? You might need to ‘source’ your bashrc or similar user profile file again, or log out and back in again.

Best wishes,
James

From: nicky9468 ***@***.***>
Date: Monday, 12 June 2023 at 2:56 pm
To: james-cole/brainageR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [james-cole/brainageR] brainageR command not found (Issue #10)

⚠ Caution: External sender


Hi,

I'm a beginner at working with codes and commands. I've tried to follow the instructions to set up brainageR, by making the directories, cloning the repository, downloading the 3 .rds files and editing the paths in the brainageR script. However, the terminal is still unable to recognise brainageR as a command.

Refer to images below for the path references:
brainageR_dir=/home/nicky155/Documents/brainageR/software/
spm_dir=/home/nicky155/Documents/MRI/SPM12/
matlab_path=/usr/local/MATLAB/R2023a/bin/matlab
FSLDIR=/home/nicky155/fsl/

[image]<https://user-images.githubusercontent.com/110340502/245163582-29e7dc82-56fb-411b-b82a-ed599c4d359e.png>

[image]<https://user-images.githubusercontent.com/110340502/245162884-bdde9b05-1802-4ddb-a1fc-2d2bad2ed9cf.png>

[image]<https://user-images.githubusercontent.com/110340502/245163208-42bc0a8b-b545-4399-960b-58d406bd879a.png>

[image]<https://user-images.githubusercontent.com/110340502/245163299-c16b65ad-771c-44bc-bf05-c1233aea27c0.png>
