### ISSUE TITLE
readlink on Mac not working on v2.1

### ISSUE THREAD

**Issue by james-cole** [james-cole/brainageR#2]
Turns out readlink on Mac doesn't have a -f option. There are several work-arounds for this for Mac users (it's not an issue for 'nix). The most simple is to edit the brainageR script and use 'realpath' instead of 'readlink'.
Alternatively you can install the GNU coreutils package and get the correct version of readlink for your system.

**Comment by biomed27** [comment]
Good Afternoon, Does "realpath" also work on Windows machine? Thanks!

**Comment by james-cole** [comment]
Hi - sorry I'm not actually sure about realpath on Windows. It would depend on which terminal environment you're using. If you can provide more details about your set up I can try to help.

**Comment by biomed27** [comment]
Good Morning James,

I hope this email finds you well. Thank you for getting back to me! I was
actually able to set the code up on my Ubuntu computer and
have everything working in place of using my Windows.

Best,
Natalie

**Comment by james-cole** [comment]
Great!

**Comment by gy94-psy** [comment]
> Good Morning James,
> 
> I hope this email finds you well. Thank you for getting back to me! I was
> actually able to set the code up on my Ubuntu computer and
> have everything working in place of using my Windows.
> 
> Best,
> Natalie
> […](#)

Hello, biomed27,  I am actually trying to run the code using Ubuntu, if you still have, can you share how you run the code on Ubuntu. Thanks in advance.

**Comment by biomed27** [comment]
> > Good Morning James,
> > I hope this email finds you well. Thank you for getting back to me! I was
> > actually able to set the code up on my Ubuntu computer and
> > have everything working in place of using my Windows.
> > Best,
> > Natalie
> > […](#)
> 
> Hello, biomed27, I am actually trying to run the code using Ubuntu, if you still have, can you share how you run the code on Ubuntu. Thanks in advance.

Hi gy94-psy,

Sure. I did not actually change the brainageR code itself. Here are the lines of code I used:
export PATH=$PATH:/home/....../brainageR/software/ ( path to where this directory is)
cd brainageR
cd T1_images (folder name of where your T1's are)

Then I just run the brainageR script as mentioned in the repo. Hope that helps!
