### ISSUE TITLE
Make installation section more explicit

### ISSUE THREAD

**Issue by RDoerfel** [james-cole/brainageR#6]
Hey! 

While I installed the package on one of my machines, I ran into some struggles, which I believe could have been avoided in the first place if the installation guide had been a little more explicit. Nothing bad; I just had some moments of confusion while installing everything. Since I expect to install it on other machines in the future, I adapted your guide a little bit to what I believe is a little more instructive and explicit. 

You can find the adapted version [here](https://github.com/RDoerfel/brainageR#installation).

If you feel like this would be an improvement to your installation guide, I'd be more than happy to open a PR to discuss and merge the changes into your repository. Otherwise, sorry for the noise :)

**Comment by james-cole** [comment]
Thanks for this contribution @RDoerfel. Please go ahead with the PR
